name: Build K29
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Derle ve Paketle
        run: |
          # -x objective-c++ : Derleyiciye dosyanın Objective-C++ olduğunu belirtir
          # -framework Foundation : Apple'ın temel kütüphanesini bağlar
          clang++ -x objective-c++ -arch arm64 -dynamiclib k29.cpp -o k29.dylib -framework Foundation
      - name: Yukle
        uses: actions/upload-artifact@v4
        with:
          name: k29-dylib
          path: k29.dylib
