name: Build K29
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Derleme ve Paketleme
        run: |
          # Dosyayı her yerde ara ve derle
          FILE=$(find . -name "k29.cpp" | head -n 1)
          clang++ -arch arm64 -dynamiclib "$FILE" -o k29.dylib -framework Foundation
      - name: Sonuc
        uses: actions/upload-artifact@v4
        with:
          name: k29-dylib
          path: k29.dylib
